name: Build

on:
  workflow_dispatch

env:
  THEOS: ""
  VERSION: "0.0.0-0"

jobs:
  fetch-and-release:
    runs-on: macos-14
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Install Dependencies
        run: |
          echo /usr/local/opt/make/libexec/gnubin >> $GITHUB_PATH
          echo /opt/homebrew/opt/make/libexec/gnubin >> $GITHUB_PATH
          HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install dpkg ldid-procursus make xcbeautify openssl@3

      - name: Checkout THEOS
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/theos
          ref: 942cd0c015f93d8c2d714ba0c69e7f420157c382
          path: theos
          submodules: recursive

      - name: Add THEOS environment variables
        run: |
          rm -rf $GITHUB_WORKSPACE/theos/sdks
          echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
          echo "THEOS_PACKAGE_SCHEME=rootless" >> $GITHUB_ENV
          echo "FINALPACKAGE=1" >> $GITHUB_ENV

      - name: Checkout SDKs
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/sdks
          ref: master
          path: ${{ env.THEOS }}/sdks

      - name: Build Packages
        run: |
          make package
          cp packages/*.deb .
          find .theos/obj -name "*.dylib" -exec cp -r {} . \;

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ env.VERSION }}
          path: |
            *.deb
            *.dylib
